# Generated by Django 3.1.7 on 2021-03-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bookID', models.IntegerField(default='-1')),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('auteurs', models.CharField(default='', max_length=1000)),
                ('cover', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TermesUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('terme', models.CharField(max_length=1000, unique=True)),
                ('urls', models.CharField(max_length=1000)),
            ],
        ),
    ]
