# Generated by Django 3.1.7 on 2021-03-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksurl',
            name='auteurs',
        ),
        migrations.RemoveField(
            model_name='booksurl',
            name='cover',
        ),
    ]
