# Generated by Django 3.1.7 on 2021-03-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0003_auto_20210322_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jaccard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('x_bookID', models.IntegerField(default='-1')),
                ('y_bookID', models.IntegerField(default='-1')),
                ('dist', models.DecimalField(decimal_places=4, default='-1', max_digits=100)),
            ],
        ),
    ]
