# Generated by Django 3.1.7 on 2021-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0005_auto_20210331_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksurl',
            name='title',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
